src/Entity/Beer.php
<?php

namespace App\Entity;

use App\Repository\BeerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BeerRepository::class)
 */
class Beer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Producer;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Graduation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getProducer(): ?string
    {
        return $this->Producer;
    }

    public function setProducer(string $Producer): self
    {
        $this->Producer = $Producer;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getGraduation(): ?string
    {
        return $this->Graduation;
    }

    public function setGraduation(string $Graduation): self
    {
        $this->Graduation = $Graduation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

src/Form/BeerFormType.php
<?php

namespace App\Form;

use App\Entity\Beer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BeerFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Producer')
            ->add('Description')
            ->add('Graduation')
            ->add('Image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Beer::class,
        ]);
    }
}

src/Controller/BeerController.php
<?php


namespace App\Controller;
// namespace App\Entity;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Beer;
use App\Manager\BeerManager;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\BeerFormType;
use Symfony\Component\HttpFoundation\Request;

class BeerController extends AbstractController
{
    /**
     * @Route ("/")
     */
    public function hola()
    {
        return new Response("Hola mundo");
    }

    /**
     * @Route("/beers", name="showBeers")
     */
    public function showBeers(EntityManagerInterface $doctrine){
        {
            $repo = $doctrine->getRepository(Beer::class);

            $beers = $repo->findAll();
    
            return $this->render(
                "/beers.html.twig", 
                ["beers"=>$beers]);
    
        }
    }

    /**
     * @Route("/beer/create", name="createBeer")
     */
    public function createBeer(Request $request, EntityManagerInterface $doctrine)
    {
        $form = $this->createForm(BeerFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $beer = $form->getData();

            $doctrine->persist($beer);
            $doctrine->flush();

            return $this->redirectToRoute("showBeers");
        }

        return $this->render(
            'insertBeer.html.twig',
            ['beerForm' => $form->createView()]
        );
    }



};

templates/base.html.twig
    <!DOCTYPE html>
<html>
 
    <head>
         <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="{{ asset('styles/main.css') }}" type="text/css" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,100&display=swap" rel="stylesheet">
        {% block stylesheets %}
            
        {% endblock %}
        <title>Bienvenido!</title>



        {% block javascripts %}
        {% endblock %}
    </head>
    
    <body>
        {# <div class="c-nav">
            <div class="c-nav__home">
                <a class="c-nav__link" href="{{path('')}}"/>
                    <div>
                      <p>Inicio</p>
                    </div>
                </a>
            </div>

            <div class="c-nav__home">
                <a class="c-nav__link" href="{{path('')}}"/>
                    <div>
                      <p>Cervezas</p>
                    </div>
                </a>
            </div>

            <div class="c-nav__home">
                <a class="c-nav__link" href="{{path('')}}"/>
                    <div>
                      <p>Añadir</p>
                    </div>
                </a>
            </div>

            <div class="c-nav__home">
                <a class="c-nav__link" href="{{path('')}}"/>
                    <div>
                      <p>Valóranos!</p>
                    </div>
                </a>
            </div>
        </div> #}
        
        {% block body %}{% endblock %}   
            
        
    </body>
    
</html>

templates/beers.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>Listado de Cervezas </h2>
        {% for beer in beers %}
            <div>
                <div class="card" style="width: 18rem;">
                    <img src="{{ beer.image }}" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ beer.name }}</h5>
                        <p class="card-text">{{ beer.description }}</p>
                       

                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock %}

{% block title %}Listado de Cervezas{% endblock %}

templates/insertBeer.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   
    {{ form_start(beerForm) }}
        {{ form_widget(beerForm) }}
        <button type="submit">Añadir</button>
    {{ form_end(beerForm) }}
{% endblock %}

{% block stylesheets %}
<style type="text/css">
    color:red
</style>
{% endblock %}